import type { Metadata } from "next";
import localFont from 'next/font/local'
import Navbar from "../components/ui/navbar/Navbar";
import "./globals.css";



const ProximaNova = localFont({
  src: '../lib/fonts/ProximaNova/Proxima Nova Alt Regular.otf',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${ProximaNova.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
